name: "GSM RPICAM HASS"
description: "GSM RPICAM add-on for capturing videos, uploading to Google Drive, and sending SMS notifications with GPS location"
version: "1.1.0"
slug: "gsm_rpicam_hass"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  3000/tcp: 8000
  8080/tcp: 8080
boot: auto
uart: true
privileged: true  # Full privileged mode for hardware access
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyUSB2
  - /dev/ttyUSB3
  - /dev/video0
  - /dev/vchiq  # Raspberry Pi camera
  - /dev/vcsm-cma  # Raspberry Pi memory
map:
  - addon_config:rw
  - share:rw
apparmor: false
host_network: true
host_dbus: true
host_ipc: true
full_access: true
environment:
  DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/run/dbus/system_bus_socket"
mounts:
  - source: /dev/bus/usb
    target: /dev/bus/usb
    type: bind
  - source: /run/dbus
    target: /run/dbus
    type: bind
  - source: /run/udev
    target: /run/udev
    type: bind
options:
  google_credentials: ""
  folder_id: "videos"
  video_directory: "/share/gsm_rpicam_videos"
  debug_mode: false
  send_early_notification: true
  include_location: true
  wait_for_gps: false
  gps_timeout: 30
schema:
  google_credentials: "str?"
  folder_id: "str"
  video_directory: "str"
  debug_mode: "bool"
  send_early_notification: "bool"
  include_location: "bool"
  wait_for_gps: "bool"
  gps_timeout: "int(0,120)"
panel_icon: "mdi:video-wireless"
panel_title: "GSM RPICAM"
webui: "http://[HOST]:[PORT:8000]"