name: "GSM RPICAM HASS"
description: "GSM RPICAM add-on for capturing videos, uploading to Google Drive, and sending SMS notifications with GPS location"
version: "1.2.1"
slug: "gsm_rpicam_hass"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  3000/tcp: 8000
boot: auto
privileged:
  - IPC_LOCK
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_MODULE
  - NET_ADMIN
  - SYS_NICE
full_access: true
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
apparmor: false
host_network: true
host_dbus: true
host_ipc: true
video: true
udev: true
tmpfs: true
environment:
  DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/run/dbus/system_bus_socket"
devicetree: true
kernel_modules: true
options:
  google_credentials: ""
  folder_id: "videos"
  video_directory: "/share/gsm_rpicam_videos"
  debug_mode: false
  send_early_notification: true
  include_location: true
  wait_for_gps: false
  gps_timeout: 30
schema:
  google_credentials: "str?"
  folder_id: "str"
  video_directory: "str"
  debug_mode: "bool"
  send_early_notification: "bool"
  include_location: "bool"
  wait_for_gps: "bool"
  gps_timeout: "int(0,120)"
panel_icon: "mdi:video-wireless"
panel_title: "GSM RPICAM"
webui: "http://[HOST]:[PORT:8000]"