name: "GSM RPICAM HASS"
description: "GSM RPICAM add-on for capturing videos, uploading to Google Drive, and sending SMS notifications"
version: "1.0.1"
slug: "gsm_rpicam_hass"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  3000/tcp: 8000
boot: auto
uart: true
privileged:
  - IPC_LOCK
  - SYS_ADMIN
  - SYS_RAWIO
devices:
  - /dev/ttyUSB0
map:
  - addon_config:rw
  - share:rw
options:
  google_credentials: ""
  folder_id: "videos"
  video_directory: "/share/gsm_rpicam_videos"
schema:
  google_credentials: "str?"
  folder_id: "str"
  video_directory: "str"